### ISSUE TITLE
Routing / Websocket issue on the evaluation screen when trying to play multiple rounds. 

### ISSUE THREAD

**Issue by joswed** [sopra-fs24-group-20/sopra-fs24-group-20-client#124]

**Comment by mirjamweibel** [comment]
also these commits, forgot to mention issue in commit message: https://github.com/sopra-fs24-group-20/sopra-fs24-group-20-client/commit/a72eddcf4696d2e1f96ae2b561e00a91401adc0e https://github.com/sopra-fs24-group-20/sopra-fs24-group-20-client/commit/2262e44cdebeacc74164eef877232d39c25d92fc
